Add BinaryHeap::from_vec_cmp_rebuild
sekineh/binary-heap-plus-rs pull request #22
Opened 2020-09-20 08:32 UTC by davidli2010

In some cases, if the vec has satified the comparator, it's no need to rebuild. So we can improve performance by set `rebuild` as `false`.

2020-09-23 04:59 UTC, sekineh requested changes
Could you please explain use cases for this?

2020-09-23 07:16 UTC, davidli2010 commented on src/binary_heap.rs
> +    pub fn from_vec_cmp_rebuild(vec: Vec<T>, cmp: C, rebuild: bool) -> Self {
Yes, the function is unsafe.

Let me explain the use case here first. 

Below is a simplified example:

```Rust

use binary_heap_plus::BinaryHeap;
use compare::Compare;
use std::cmp::Ordering;

#[derive(Debug)]
struct ComparatorWithoutNone;

impl Compare<Option<i32>> for ComparatorWithoutNone {
    fn compare(&self, l: &Option<i32>, r: &Option<i32>) -> Ordering {
        // l and r can not be None.
        l.unwrap().cmp(&r.unwrap())
    }
}

#[derive(Debug)]
struct Comparator;

impl Compare<Option<i32>> for Comparator {
    fn compare(&self, l: &Option<i32>, r: &Option<i32>) -> Ordering {
        match (l, r) {
            (Some(l), Some(r)) => l.cmp(r),
            (Some(_), None) => Ordering::Greater,
            (None, Some(_)) => Ordering::Less,
            (None, None) => Ordering::Equal,
        }
    }
}

fn main() {
    let mut heap = BinaryHeap::from_vec_cmp(vec![], ComparatorWithoutNone);
    // only insert integers
    heap.push(Some(3));
    heap.push(Some(1));
    heap.push(Some(5));

    let mut heap = unsafe {
        BinaryHeap::from_vec_cmp_rebuild(heap.into_vec(), Comparator, false)
    };
    // insert integer and None
    heap.push(None);
    heap.push(Some(2));
    heap.push(None);

    println!("heap: {:?}", heap.into_iter_sorted().collect::<Vec<_>>());
}
```

Here we define two comparator `ComparatorWithoutNone` and `Comparator`. `Comparator` is compatiable with `ComparatorWithoutNone`. 

Generally, we can always use `Comparator`. But when we guarantee there are no `None`s,  we can use `ComparatorWithoutNone`  instead.

Maybe the expample here is rediculous. In a real use case, `ComparatorWithoutNone` means a comparator with higher performance for specified values and `Comparator` means a general comparator with lower performance.

2020-09-23 07:57 UTC, sekineh commented on src/binary_heap.rs
> +    pub fn from_vec_cmp_rebuild(vec: Vec<T>, cmp: C, rebuild: bool) -> Self {
It looks like a perfect explanation!

2020-09-23 08:17 UTC, sekineh commented
I like the idea of adding `unsafe` optimized version of `BinaryHeap` constructor which skips the rebuild process.

I'm going to merge this PR# after you add two changes below:
- Add `CHANGELOG.md` entry for this.
```
## [Unreleased]

### Added
* description here
```
- Rename the function name from `from_vec_cmp_rebuild()` to `from_vec_cmp_raw()`. 
  - (It's just my taste; The purpose of this function is to skip `rebuild` process, so the `_rebuild` suffix feels oposite to me.)

Thanks!

2020-09-23 08:37 UTC, merged

2020-09-23 08:49 UTC, davidli2010 commented
There is another use case similar with this function. If we only have a mutable reference to `BinaryHeap`, then we cannot call `into_vec()` to get the vec. So I think it need to add another function `BinaryHeap::replace_cmp(&mut self, cmp: C, rebuild: bool)` to replace the comparator at runtime.

I will push another merge request if you think it's OK.

2020-09-24 02:09 UTC, sekineh commented
> There is another use case similar with this function. If we only have a mutable reference to `BinaryHeap`, then we cannot call `into_vec()` to get the vec. So I think it need to add another function `BinaryHeap::replace_cmp(&mut self, cmp: C, rebuild: bool)` to replace the comparator at runtime.
> 
> I will push another merge request if you think it's OK.

In that case, I'd like to see the combination of two API.
- safe version `BinaryHeap::replace_cmp(&mut self, cmp: C)`
  - similar to `from_vec_cmp()`
  - it's safe because it always rebuilds!
- `unsafe` version `BinaryHeap::replace_cmp_raw(&mut self, cmp: C, rebuild: bool)`
  - similar to `from_vec_cmp_raw()`